apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwks-server
  namespace: jwks
  labels:
    app: jwks-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwks-server
  template:
    metadata:
      labels:
        app: jwks-server
    spec:
      containers:
        - name: jwks-server
          image: pszeto/jwks-server:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: KEY_SIZE
              value: "2048"
